services:
  fastapi:
    build: .
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    ports:
      - "8000:8000"
    networks:
      - lgtm
      
networks:
  lgtm:
    name: lgtm
    external: true